import { type Metadata } from 'next'
import {
  ClerkProvider,

} from '@clerk/nextjs' 
import './globals.css'
 

export const metadata: Metadata = {
  title: 'chat-fusion-ai',
  description: 'Generated by chat-fusion-ai',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
       <body>{children}</body>
      </html>
    </ClerkProvider>
  )
}